[project]
name = "compliance-iq-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.139.0",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.3.5",
    "langchain-postgres>=0.0.17",
    "langchain-text-splitters>=1.1.2",
    "path>=17.1.1",
    "pathlib>=1.0.1",
    "pypdf>=6.14.2",
    "python-multipart>=0.0.32",
    "uvicorn>=0.51.0",
    "psycopg>=3.3.4",
    "streamlit>=1.59.2",
    "tavily-python>=0.7.26",
    "langchain>=1.3.14",
    "langchain-openapi>=0.1.1",
]

